# Generated by Django 3.2.16 on 2024-02-29 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='price',
            field=models.IntegerField(default=10, help_text='Рекомендованная розничная цена', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(help_text='Необязательное поле', max_length=20, verbose_name='Фамилия'),
        ),
    ]
